import { frame, esc } from './pages.mjs';

const categories={revenue:'Выручка',revenue_return:'Финансовые возвраты',acquiring:'Эквайринг',logistics:'Логистика',storage:'Хранение',acceptance:'Приёмка',penalty:'Штрафы и пени',deduction:'Удержания',commission_adjustment:'Коррекция комиссии',other_adjustment:'Другие корректировки',promotion:'Продвижение WB',pickup_reward:'Вознаграждение ПВЗ',wb_reward_without_vat:'Вознаграждение WB без НДС',wb_reward_vat:'НДС вознаграждения WB',return_wb_expense_reversal:'Возврат расходов WB',wb_row_rounding_adjustment:'Коррекция округления WB',cost_of_goods:'Себестоимость',packaging:'Упаковка',software_services:'Программные сервисы',external_promotion:'Внешнее продвижение',agency_services:'Услуги агентства',other_external:'Другие дополнительные расходы',estimated_usn_tax:'Налог УСН',daily_tax_range:'Налог за период'};
const reasons={drilldown_period_unavailable:'Нет точного покрытия выбранного периода',drilldown_publication_incompatible:'Поколения публикации несовместимы',drilldown_source_unsupported:'Для этой публикации нет поддерживаемого источника',drilldown_frozen_source_missing:'Не найдена подтверждённая сохранённая версия источника',drilldown_reconciliation_mismatch:'Сохранённые суммы или доказательства не сходятся',drilldown_metric_unavailable:'Недостаточно данных для этого показателя',drilldown_category_unsupported:'Категория пока не поддерживается',report_coverage_incomplete:'Покрытие финансовыми отчётами неполное',operation_unclassified:'Есть операции с неподтверждённой классификацией',cost_missing:'Не указана себестоимость',tax_base_negative_unverified:'Отрицательная налоговая база не подтверждена',tax_setting_missing:'Не сохранены налоговые настройки'};
const qualityLabels={complete:'Полные данные',partial:'Неполные данные',unavailable:'Недоступно'};
const evidenceLabels={matched:'Источники подтверждены',unchecked:'Остальные страницы источников не проверены',unavailable:'Доказательства недоступны'};
const metricLabels={revenue:'Выручка',wbExpenses:'Расходы WB',costOfGoods:'Себестоимость',externalExpenses:'Дополнительные расходы',tax:'Налог',availableResultBeforeTax:'Доступный результат до налога',availableResultAfterTax:'Доступный результат после налога'};
const checkLabels={selected_products_before_tax:'Результат выбранных SKU до налога',store_before_tax:'Общие строки магазина до налога',available_before_tax:'Доступный итог до налога',tax_contributions:'Налоговые вклады',available_after_tax:'Доступный итог после налога',tax_aggregate_amount:'Ограничение суммы налога',tax_aggregate_base:'Ограничение налоговой базы',tax_fact_numerator:'Сохранённый налоговый числитель',overview_revenue:'Выручка обзора',overview_wbExpenses:'Расходы обзора',overview_costOfGoods:'Себестоимость обзора',overview_toTransfer:'К перечислению по отчётам WB',overview_composition:'Состав финансового обзора',tax_basis_evidence:'Источники налоговой базы',group_contributions:'Сохранённые вклады категории'};
const contextKeys=['storeId','publicationSource','publicationId','periodStart','periodEnd'];
function contextParams(context={}){return {storeId:context.storeId,publicationSource:context.publication?.source,publicationId:context.publication?.id,periodStart:context.period?.start,periodEnd:context.period?.end};}
function listState(options){return {...options,...options.listState,cursor:options.listState?.cursor??options.listCursor??options.cursor};}
function query(context,options={},extra={},list=false){
  const state=listState(options),params=new URLSearchParams();
  const values={...contextParams(context),storeId:context?.storeId??options.selectedStoreId,
    periodStart:context?.period?.start??options.period?.start,periodEnd:context?.period?.end??options.period?.end,
    search:state.search,sort:state.sort,limit:state.limit,...(list?{cursor:state.cursor}:{listCursor:state.cursor}),...extra};
  for(const[key,value]of Object.entries(values))if(value!==null&&value!==undefined&&value!=='')params.set(key,String(value));
  return params.toString();
}
function href(path,context,options,extra={},list=false){return `${path}?${query(context,options,extra,list)}`;}
function anchor(path,label,context,options,extra={},list=false){return `<a href="${esc(href(path,context,options,extra,list))}">${esc(label)}</a>`;}
function money(value){
  const match=typeof value==='string'&&value.match(/^(-?)(\d+)(?:\.(\d+))?$/);
  if(!match)return '<span class="sku-unavailable">Недоступно</span>';
  const fraction=match[3]??'',cents=BigInt(match[2]+fraction.padEnd(2,'0').slice(0,2))+(fraction[2]>='5'?1n:0n);
  const digits=cents.toString().padStart(3,'0'),whole=digits.slice(0,-2).replace(/\B(?=(\d{3})+(?!\d))/g,' ');
  return `<span class="sku-money" title="Точная сумма: ${esc(value)} ₽">${match[1]&&cents!==0n?'−':''}${whole},${digits.slice(-2)} ₽</span>`;
}
function reasonList(values=[],heading='Причины'){
  if(!values.length)return '';
  return `<div class="sku-reasons"><strong>${esc(heading)}</strong><ul>${values.map(reason=>{const code=typeof reason==='string'?reason:reason.code;const scope=typeof reason==='object'?reason.scope:null;return `<li>${esc(reasons[code]??`Причина пока не описана (${code??'без кода'})`)}${scope?` · ${esc(scope==='store'?'магазин / период':scope==='selected_product'?'SKU':scope)}`:''}</li>`;}).join('')}</ul></div>`;
}
function badge(quality){return `<span class="sku-status">${esc(qualityLabels[quality]??qualityLabels.unavailable)}</span>`;}
function reconciliation(value,label='Сверка денег'){
  const status=value?.status;
  return `<details class="sku-reconciliation"><summary>${esc(label)}: ${esc(status==='matched'?'доступные суммы сходятся':status==='mismatch'?'обнаружено несоответствие':'недоступна')}</summary><p>Сверка доступных сумм не подтверждает полноту финансового результата или источники остальных страниц.</p>${(value?.checks??[]).map(check=>`<div><p>${esc(checkLabels[check.code]??'Проверка доступной суммы')} · ${esc(check.status==='matched'?'сходится':check.status==='mismatch'?'не сходится':'недоступно')} · ожидается ${esc(check.expectedAmount??check.expected??'недоступно')}, прочитано ${esc(check.actualAmount??check.actual??'недоступно')}</p>${check.reason?reasonList([check.reason]):''}</div>`).join('')}</details>`;
}
function metadata(context,options){
  if(!context?.publication)return `<section class="sku-context">${badge('unavailable')}<p>Опубликованный финансовый результат пока недоступен. Выберите магазин и период на обзоре; после публикации здесь появится расшифровка.</p></section>`;
  const coverage=context.coverage?.covered,update=context.update;
  const updateLabel={current:'Обновление завершено',queued:'Обновление в очереди',pending:'Обновление ожидается',running:'Результат обновляется',retry:'Обновление будет повторено',failed:'Обновление не завершилось'}[update?.status]??'Состояние обновления неизвестно';
  return `<section class="sku-context" aria-label="Контекст финансовой публикации"><p>${esc(context.period?.start)} — ${esc(context.period?.end)} · ${badge(context.quality)}</p><p>Основание результата: ${esc(context.resultBasis==='after_tax'?'после налога':context.resultBasis==='before_tax'?'до налога':'недоступно')}. Методика: ${esc(context.method?.version??'не указана')}.</p><p>Фактическое покрытие: ${coverage?`${esc(coverage.start)} — ${esc(coverage.end)}`:'не подтверждено'} · ${context.coverage?.complete?'покрытие подтверждено':'покрытие неполное'}</p><p>Публикация от ${esc(context.publication.publishedAt??'неизвестной даты')} · <span class="sku-id">${esc(context.publication.id)}</span></p><p role="status">${esc(updateLabel)}. Показан сохранённый результат.${update?.availablePublicationId?` ${anchor(options.publicationPath??'/sku','Открыть новую публикацию',context,options,{publicationId:update.availablePublicationId,cursor:null,listCursor:null},true)}`:''}</p>${reasonList(context.missingReasons,'Причины периода')}</section>`;
}
function productTitle(product){return product?.name||'Название товара не сохранено';}
function productMeta(product={}){const image=typeof product.imageUrl==='string'&&/^https:\/\//i.test(product.imageUrl)?`<img class="sku-product-image" src="${esc(product.imageUrl)}" alt="${esc(productTitle(product))}" loading="lazy">`:'';return `${image}<p class="muted">Артикул продавца: ${esc(product.sellerArticle??'не сохранён')} · Артикул WB: ${esc(product.wbArticle??'не сохранён')}${product.isHistorical?' · Исторический / удалённый товар':''}</p><small class="muted">Названия, артикулы и фотографии могут отражать текущие данные каталога.</small>`;}
function groupsView(groups,context,options,productId){return groups.length?groups.map(group=>`<details class="sku-group"><summary>${esc(categories[group.categoryCode]??`Неизвестная категория (${group.categoryCode})`)} · ${money(group.amountSigned)}</summary><p>Знаковый вклад · исходных строк: ${esc(group.lineCount)} · ${esc(evidenceLabels[group.evidenceStatus]??evidenceLabels.unchecked)}</p>${reasonList(group.missingReasons)}${anchor('/sku/sources','Сохранённые вклады и источники',context,options,{groupKey:group.groupKey,...(productId?{productId}:{scope:'store'})})}${group.taxBasisAvailable?` · ${anchor('/sku/sources','Сохранённая налоговая база',context,options,{groupKey:group.groupKey,productId,taxBasis:'1'})}`:''}</details>`).join(''):'<p>Сохранённых категорий нет; это само по себе не подтверждает нулевой результат.</p>';}
function metricView(item,context,options){return `<dl class="sku-metrics">${Object.entries(metricLabels).map(([key,label])=>{const metric=item.metrics?.[key];return `<div><dt>${esc(label)}</dt><dd>${money(metric?.amount)} · ${badge(metric?.availability)}${reasonList(metric?.missingReasons)}${(metric?.groupKeys??[]).map(groupKey=>` ${anchor('/sku/sources',`Источники: ${categories[item.groups?.find(g=>g.groupKey===groupKey)?.categoryCode]??'категория'}`,context,options,{productId:item.productId,groupKey})}`).join('')}</dd></div>`;}).join('')}</dl>`;}
function render(user,stores,data,options,route,body){const context=data?.context;return frame({...user,stores},route,`<link rel="stylesheet" href="/sku.css"><section class="sku-page">${body}</section>`,stores,{...contextParams(context),periodStart:context?.period?.start??options.period?.start,periodEnd:context?.period?.end??options.period?.end});}
export function skuListPage(user,stores=[],data=null,options={}){
  const context=data?.context,state=listState(options),fixed=contextParams(context);
  const filter=context?.publication?`<form class="sku-filter" method="get" action="/sku">${contextKeys.map(key=>`<input type="hidden" name="${key}" value="${esc(fixed[key])}">`).join('')}<label>Поиск по названию или артикулу<input name="search" value="${esc(state.search??'')}" maxlength="256" type="search"></label><label>Сортировка<select name="sort">${[['result_asc','Результат: по возрастанию'],['result_desc','Результат: по убыванию'],['revenue_asc','Выручка: по возрастанию'],['revenue_desc','Выручка: по убыванию']].map(([key,label])=>`<option value="${key}" ${(state.sort??'result_asc')===key?'selected':''}>${label}</option>`).join('')}</select></label><label>Товаров на странице<input name="limit" type="number" min="1" max="100" value="${esc(state.limit??25)}"></label><button class="outline-button" type="submit">Показать</button></form>`:'';
  const items=data?.items??[];
  const rows=items.map(item=>`<article class="sku-item"><h2>${anchor('/sku/card',productTitle(item),context,options,{productId:item.productId})}</h2>${productMeta(item)}${badge(item.quality)}${reasonList(item.missingReasons,'Причины SKU')}${metricView(item,context,options)}</article>`).join('');
  const totals=context?.totals;
  return render(user,stores,data,options,'/sku',`<h1>Товары (SKU)</h1>${anchor('/overview','Вернуться к обзору',context,options)}${metadata(context,options)}${filter}${context?.publication?`<p>Найдено: ${esc(data.totalItems??items.length)} · SKU в финансовой области публикации: ${esc(data.scopeItemCount??context.scope?.productIds?.length??0)}. Поиск не меняет итог магазина.</p>`:''}${rows||'<p>Товары с ненулевыми показателями не найдены. Проверьте поиск и доступность публикации; отсутствие строк не означает ноль.</p>'}${data?.nextCursor?`<nav aria-label="Страницы SKU">${anchor('/sku','Следующая страница товаров',context,options,{cursor:data.nextCursor},true)}</nav>`:''}${context?.publication?`<section class="sku-store"><h2>Общие строки и итог магазина</h2><p>Общие расходы не распределяются между SKU. ${context.scope?.includesStoreResult?'Включены в итог по методике публикации.':'Не включены в итог по методике публикации.'}</p>${groupsView(data.storeLines??[],context,options,null)}<dl class="sku-metrics"><div><dt>Выбранные SKU до налога</dt><dd>${money(totals?.selectedProductsResultBeforeTax)}</dd></div><div><dt>Общие строки до налога</dt><dd>${money(totals?.storeLevelResultBeforeTax)}</dd></div><div><dt>Доступный итог магазина до налога</dt><dd>${money(totals?.availableResultBeforeTax)}</dd></div><div><dt>Доступный итог магазина после налога</dt><dd>${money(totals?.availableResultAfterTax)}</dd></div></dl>${reconciliation(data.reconciliation)}</section>`:''}`);
}
export function skuCardPage(user,stores=[],data=null,options={}){
  const context=data?.context,item=data?.item;
  return render(user,stores,data,options,'/sku/card',`${anchor('/sku','Вернуться к списку SKU',context,options,{},true)}<h1>${esc(productTitle(item))}</h1><p>Финансовый результат отдельного SKU. Общие строки магазина показываются в списке SKU.</p>${item?productMeta(item):''}${metadata(context,options)}${item?`${badge(item.quality)}${reasonList(item.missingReasons,'Причины SKU')}${metricView(item,context,options)}<h2>Состав результата SKU</h2>${groupsView(item.groups??[],context,options,item.productId)}${reconciliation(data.reconciliation)}`:'<p>Карточка финансового результата недоступна.</p>'}`);
}
const sourceLabels={sourceKind:'Тип источника',sourceField:'Поле исходной суммы',sourceAmount:'Исходная сумма (точная)',unitCost:'Цена единицы (точная)',effectiveFrom:'Дата действия цены',quantity:'Количество источника',accountingDate:'Учётная дата',operationType:'Операция',variantId:'Вариант',reportRowId:'Строка отчёта',reportVersionId:'Замороженная версия отчёта',reportNormalizationId:'Замороженная нормализация',operationVersionId:'Версия операции',financialComponentId:'Финансовый компонент',operationLinkId:'Зафиксированная связь возврата',costVersionId:'Версия себестоимости',expenseVersionId:'Версия дополнительного расхода',taxComputationId:'Сохранённый расчёт налога',taxSettingVersionId:'Версия налоговой настройки',taxAmount:'Сохранённая сумма налога',taxableBase:'Налоговая база (точная)',basisEvidenceCount:'Количество источников базы'};
const sourceKinds={financial_component:'Компонент отчёта WB',expense_version:'Дополнительный расход',sale_cost:'Себестоимость продажи',return_cost:'Себестоимость возврата',tax_computation:'Сохранённый расчёт налога',report_row:'Строка отчёта WB',return_wb_expense_reversal:'Возврат расходов WB',wb_row_rounding_adjustment:'Коррекция округления WB'};
function fields(value,labels){return Object.entries(labels).filter(([key,label])=>label&&value?.[key]!=null&&typeof value[key]!=='object').map(([key,label])=>{let display=value[key];if(key==='sourceKind')display=sourceKinds[display]??'Сохранённый источник';if(key==='operationType')display={sale:'Продажа',return:'Возврат',adjustment:'Корректировка'}[display]??'Операция отчёта WB';if(key==='sourceField')display=({retailAmount:'Сумма продажи / возврата',deliveryRub:'Логистика',storageFee:'Хранение',penalty:'Штраф',deduction:'Удержание',acceptance:'Приёмка'}[display]??'Денежное поле отчёта WB')+` (${display})`;return `<div><dt>${esc(label)}</dt><dd>${esc(display)}</dd></div>`;}).join('');}
function sourceView(source){
  if(!source)return '<p>Источник недоступен. Сохранённый вклад не заменён нулём.</p>';
  const recognition={on_date:'В указанную дату',evenly_over_period:'Равномерно за период'}[source.recognitionMethod];
  const variant=source.variant;
  return `${source.variantId||variant?`<p>Вариант: ${variant?`${esc(variant.sizeLabel??'размер не указан')} · ${esc(variant.colorLabel??'цвет не указан')}${variant.isHistorical?' · исторический вариант':''}`:'Вариант не определён'}${Array.isArray(variant?.barcodes)&&variant.barcodes.length?` · Штрихкоды: ${variant.barcodes.map(esc).join(', ')}`:''}</p>`:''}<dl class="sku-source-fields">${fields(source,{...sourceLabels,variantId:undefined})}${source.period?`<div><dt>Период расхода</dt><dd>${esc(source.period.start)} — ${esc(source.period.end)}</dd></div>`:''}${source.recognitionMethod?`<div><dt>Правило признания</dt><dd>${esc(recognition??source.recognitionMethod)}</dd></div>`:''}${fields(source.raw,{reportId:'Номер отчёта WB',rrdId:'Номер строки WB',nmId:'Артикул WB',dateFrom:'Начало отчёта',dateTo:'Конец отчёта',docTypeName:'Документ WB',sellerOperName:'Операция WB',currency:'Валюта источника'})}</dl>${(source.segments??[]).map(segment=>taxView(segment)).join('')}${source.originalSale?`<details><summary>Исходная продажа для возврата</summary>${sourceView(source.originalSale)}</details>`:''}`;
}
function taxView(value){return `<dl class="sku-source-fields">${fields(value,{id:'Сохранённый факт / сегмент налога',generationId:'Поколение факта',taxSettingVersionId:'Версия настройки налога',accountingDate:'Дата налогового факта',start:'Начало сегмента',end:'Конец сегмента',taxableBase:'База сегмента (точная)',taxBaseUnrounded:'База факта до округления',taxNumeratorUnrounded:'Налоговый числитель до округления',taxRateFraction:'Ставка, доля единицы',rateFraction:'Ставка сегмента, доля единицы'})}</dl>`;}
function contributionView(item){const basis=item.basisContributionAmount!=null;return `<article class="sku-contribution"><h3>${basis?'Вклад в налоговую базу':'Сохранённый вклад в сумму'}: ${money(basis?item.basisContributionAmount:item.contributionAmount)}</h3><p>Точное значение: ${esc(basis?item.basisContributionAmount:item.contributionAmount)}${basis?' · Это база, а не прямой денежный вклад в налог.':''}</p><p>${esc(evidenceLabels[item.evidenceStatus]??evidenceLabels.unavailable)}</p>${reasonList(item.missingReasons)}${item.accountingDate?`<p>Дата признания: ${esc(item.accountingDate)}</p>`:''}${item.taxComputationId?`<p>Сохранённый расчёт налога: ${esc(item.taxComputationId)}</p>`:''}${item.taxFact?taxView(item.taxFact):''}${item.segment?taxView(item.segment):''}<details><summary>Проверенные поля источника</summary>${sourceView(item.source)}</details></article>`;}
export function skuSourcesPage(user,stores=[],data=null,options={}){
  const context=data?.context,group=data?.group,product=data?.product;
  const taxBasis=options.taxBasis===true||options.taxBasis==='1';
  const basis=taxBasis||data?.items?.some(item=>item.basisContributionAmount!=null);
  const extra={...(data?.situation?{situationId:data.situation.id}:{}),groupKey:group?.groupKey,...(group?.scope==='store'?{scope:'store'}:{productId:group?.productId}),...(taxBasis?{taxBasis:'1'}:{})};
  return render(user,stores,data,options,'/sku/sources',`${data?.situation?`<p>${anchor('/situation','Вернуться к ситуации',context,options,{situationId:data.situation.id})}</p>`:''}${group?.scope==='store'?anchor('/sku','Вернуться к списку SKU',context,options,{},true):anchor('/sku/card','Вернуться к карточке SKU',context,options,{productId:group?.productId})}<h1>${esc(categories[group?.categoryCode]??'Источники результата')}</h1><p>${group?.scope==='store'?'Общие строки магазина':`SKU: ${esc(productTitle(product))}`}</p>${product?productMeta(product):''}${metadata(context,options)}${group?`<p>Сохранённая знаковая сумма категории: ${money(group.amountSigned)}</p>`:''}<p>Проверка источников этой страницы: ${esc(evidenceLabels[data?.evidenceStatus]??evidenceLabels.unavailable)}. Область проверки источников: ${data?.sourceValidationScope==='page'?'выданная страница':'не подтверждена'}.</p>${basis?'<p>Показана сохранённая налоговая база. Итог налога определяется сохранёнными фактами, ставками и правилами округления; сумма базы не является суммой налога.</p>':'<p>Исходная сумма или цена источника может отличаться от его вклада в результат.</p>'}${reasonList(data?.missingReasons)}${reconciliation(data?.reconciliation,'Сверка всей группы')}${data?.moneyReconciliation?reconciliation(data.moneyReconciliation,'Сверка финансовой области публикации'):''}${(data?.taxSummary??[]).length?`<section><h2>Сохранённый налог</h2>${data.taxSummary.map(contributionView).join('')}</section>`:''}<h2>${basis?'Источники налоговой базы':'Вклады и источники'}</h2><p>Всего вкладов: ${esc(data?.totalItems??'неизвестно')}.</p>${(data?.items??[]).map(contributionView).join('')||'<p>Доступных вкладов на этой странице нет. Это не подтверждает нулевую сумму.</p>'}${group?.taxBasisAvailable&&!basis?anchor('/sku/sources','Раскрыть сохранённую налоговую базу',context,options,{...extra,taxBasis:'1'}):''}${data?.nextCursor?`<nav aria-label="Страницы источников">${anchor('/sku/sources','Следующая страница источников',context,options,{...extra,cursor:data.nextCursor})}</nav>`:''}`);
}

export const publishedPageView={money,metadata,reasonList,badge,reconciliation,productTitle,productMeta,contextParams,query,categories};
