import { selectStoreOrder, storeSelectionUrl } from '../stores/store-selection.mjs';
import { createHash } from 'node:crypto';
import { createExpenseCsvExport, createExpenseCsvTemplate, expenseImportMaxBytes, parseExpenseFile } from './expense-import.mjs';
const expenseErrors={expense_file_empty:'Файл не содержит строк расходов.',expense_file_too_large:'Файл больше 5 МБ.',expense_file_expanded_too_large:'Распакованный Excel-файл слишком большой или содержит слишком много частей.',expense_file_type:'Поддерживаются файлы CSV, TSV и XLSX.',expense_legacy_xls:'Сохраните старый XLS как XLSX или CSV и загрузите снова.',expense_file_encoding:'Сохраните CSV в кодировке UTF-8.',expense_file_invalid_csv:'Не удалось прочитать CSV.',expense_file_invalid_excel:'Не удалось прочитать Excel-файл.',expense_formula_cell:'Замените формулы вычисленными значениями.',expense_columns_missing:'Не найдены обязательные столбцы расходов.',expense_duplicate_columns:'В файле повторяются служебные столбцы.',expense_too_many_columns:'В файле больше 30 столбцов.',expense_too_many_rows:'Один файл может содержать не более 10 000 строк.',expense_invalid_amount:'Сумма должна быть больше нуля и содержать не более четырёх знаков после запятой.',expense_invalid_category:'Неизвестная категория расхода.',expense_invalid_recognition_method:'Неизвестный способ признания.',expense_invalid_date:'Некорректная дата.',expense_invalid_period:'Конец периода раньше начала.',expense_period_end_missing:'Укажите конец периода.',expense_on_date_period_mismatch:'Для расхода на дату начало и конец периода должны совпадать.',expense_invalid_id:'Некорректный ID расхода.',expense_invalid_article:'Некорректный артикул WB.',expense_invalid_channel_name:'Название канала слишком длинное.',expense_invalid_description:'Описание слишком длинное.',multipart_required:'Выберите файл для загрузки.',multipart_invalid:'Не удалось прочитать загруженный файл.',too_large:'Файл больше 5 МБ.'};
function expenseErrorMessage(error){const message=expenseErrors[error?.message]??'Не удалось сохранить дополнительные расходы.';return error?.rowNumber?`Строка ${error.rowNumber}: ${message}`:message;}
export function createExpensesRoutes({ listStores, getExpenseState, send, sendBuffer, redirect, sendExpenses, sameOrigin, takeLimit, form, saveExpense, voidExpense, multipart, importExpenses }) {
 async function dispatch(req,res,url,current){
 if(req.method==='GET'&&['/expenses/template.csv','/expenses/export.csv'].includes(url.pathname)){if(!current)return redirect(res,'/login');const stores=await listStores(current.user_id),store=stores.find(item=>item.id===(url.searchParams.get('storeId')||stores[0]?.id));if(!store||store.selectable===false)return send(res,404,'Магазин не найден.');const state=await getExpenseState(current.user_id,store.id),content=url.pathname.endsWith('template.csv')?createExpenseCsvTemplate():createExpenseCsvExport((state.expenses??[]).map(item=>({expenseId:item.id,wbArticle:item.wb_article,category:item.category,amount:item.amount,periodStart:item.period_start,periodEnd:item.period_end,recognitionMethod:item.recognition_method,channelName:item.channel_name,description:item.description,state:item.state})));return sendBuffer(res,200,content,{'content-type':'text/csv; charset=utf-8','content-disposition':`attachment; filename="expenses-${new Date().toISOString().slice(0,10)}.csv"`});}
 if(req.method==='POST'&&url.pathname==='/expenses'){
  if(!current)return redirect(res,'/login');if(!sameOrigin(req))return send(res,403,'Запрос отклонён.');let stores;try{stores=selectStoreOrder(await listStores(current.user_id),url.searchParams.get('storeId'));}catch(error){if(error.message==='store_not_found')return send(res,404,'Магазин не найден.');throw error;}const limit=await takeLimit(`expense-write:${current.user_id}`,30,15);
  if(!limit.allowed)return sendExpenses(res,429,current,stores,{error:'Слишком много изменений. Повторите через 15 минут.'});
  try{const d=await form(req),store=stores.find(item=>item.id===d.storeId);if(!store||store.selectable===false)throw new Error('store_not_found');stores=selectStoreOrder(stores,store.id);await saveExpense(current.user_id,{storeId:store.id,expenseId:d.expenseId,productId:d.productId,category:d.category,amount:d.amount,periodStart:d.periodStart,periodEnd:d.periodEnd,recognitionMethod:d.recognitionMethod,channelName:d.channelName,description:d.description});return redirect(res,storeSelectionUrl('/expenses?saved=1',store.id));}
  catch(error){const messages={store_not_found:'Магазин не найден.',expense_write_forbidden:'Недостаточно прав для изменения расходов.',expense_not_found:'Расход не найден.',expense_scope_immutable:'Нельзя изменить привязку существующего расхода. Аннулируйте его и создайте новый.',expense_product_invalid:'Выбранный товар не найден.',expense_category_invalid:'Выберите допустимую категорию.',expense_amount_invalid:'Введите сумму больше нуля.',expense_period_invalid:'Проверьте даты периода.',expense_recognition_invalid:'Для расхода на дату начало и конец должны совпадать.',expense_text_invalid:'Сократите название канала или описание.'};return sendExpenses(res,error.message==='expense_write_forbidden'?403:error.message==='store_not_found'||error.message==='expense_not_found'?404:422,current,stores,{error:messages[error.message]??'Не удалось сохранить расход.'});}
 }
 if(req.method==='POST'&&url.pathname==='/expenses/void'){
  if(!current)return redirect(res,'/login');if(!sameOrigin(req))return send(res,403,'Запрос отклонён.');let stores;try{stores=selectStoreOrder(await listStores(current.user_id),url.searchParams.get('storeId'));}catch(error){if(error.message==='store_not_found')return send(res,404,'Магазин не найден.');throw error;}
  try{const d=await form(req),store=stores.find(item=>item.id===d.storeId);if(!store||store.selectable===false)throw new Error('store_not_found');stores=selectStoreOrder(stores,store.id);await voidExpense(current.user_id,{storeId:store.id,expenseId:d.expenseId});return redirect(res,storeSelectionUrl('/expenses?voided=1',store.id));}
  catch(error){return sendExpenses(res,error.message==='expense_write_forbidden'?403:error.message==='store_not_found'||error.message==='expense_not_found'?404:422,current,stores,{error:error.message==='expense_write_forbidden'?'Недостаточно прав для изменения расходов.':error.message==='expense_not_found'?'Расход не найден.':'Не удалось аннулировать расход.'});}
 }
 if(req.method==='POST'&&url.pathname==='/expenses/import'){
  if(!current)return redirect(res,'/login');if(!sameOrigin(req))return send(res,403,'Запрос отклонён.');let stores;try{stores=selectStoreOrder(await listStores(current.user_id),url.searchParams.get('storeId'));}catch(error){if(error.message==='store_not_found')return send(res,404,'Магазин не найден.');throw error;}const limit=await takeLimit(`expense-import:${current.user_id}`,10,15);
  if(!limit.allowed)return sendExpenses(res,429,current,stores,{error:'Слишком много загрузок. Повторите через 15 минут.'});
  try{const upload=await multipart(req,expenseImportMaxBytes+65536),store=stores.find(item=>item.id===upload.fields.storeId),file=upload.files.file;if(!store||store.selectable===false)throw new Error('store_not_found');stores=selectStoreOrder(stores,store.id);if(!file?.fileName||!file.buffer?.length)throw new Error('expense_file_empty');const rows=await parseExpenseFile(file),checksum=createHash('sha256').update(file.buffer).digest('hex'),result=await importExpenses(current.user_id,{storeId:store.id,fileName:file.fileName,checksum,rows});if(!result.ok)return sendExpenses(res,422,current,stores,{error:'Файл не применён. Исправьте отмеченные строки и загрузите его снова.',importErrors:result.errors});return redirect(res,storeSelectionUrl('/expenses?imported=1',store.id));}
  catch(error){if(error.message==='expense_write_forbidden')return sendExpenses(res,403,current,stores,{error:'Недостаточно прав для изменения расходов.'});if(error.message==='store_not_found')return sendExpenses(res,404,current,stores,{error:'Магазин не найден.'});return sendExpenses(res,error.message==='too_large'||error.message==='expense_file_too_large'?413:422,current,stores,{error:expenseErrorMessage(error)});}
 }
 }
 return async function handleExpenses(req,res,url,current){
  const matches=(req.method==='GET'&&['/expenses/template.csv','/expenses/export.csv'].includes(url.pathname))||(req.method==='POST'&&['/expenses','/expenses/void','/expenses/import'].includes(url.pathname));
  if(!matches)return false;
  await dispatch(req,res,url,current);
  return true;
 };
}
