import http from 'node:http';import{readFile}from'node:fs/promises';import path from'node:path';
import{createSessionToken,createVerificationCode,hashPassword,hashToken,normalizeEmail,requiresEmailVerification,validatePasswordChange,validateRegistration,verifyPassword}from'./auth.mjs';
import{addProductsToSelection,confirmProductSelection,consumeChallenge,consumeOauthState,createPendingStore,deleteSession,findOrCreateYandexUser,findPasswordUser,findSession,getBillingSummary,getCatalogState,getPasswordCredential,listStores,markVerified,migrate,pool,registerUser,replacePassword,saveChallenge,saveOauthState,saveSession,saveWbConnection,takeLimit,updateProfile}from'./db.mjs';
import{sendVerificationCode}from'./email.mjs';import{authPage,verifyPage}from'./views.mjs';
import { overviewPage, passwordPage, productsPage, settingsPage, tariffPage, placeholderPage, storeOnboardingPage, uiRoutes } from './ui.mjs';
import { encryptSecret } from './secrets.mjs';import { verifyWbToken } from './wb.mjs';
import { scheduleCatalogSync } from './catalog-sync.mjs';
const port=Number(process.env.PORT??3000),days=30,dummyHash=await hashPassword('dummy-password-for-equal-work');
const yandexEnabled=Boolean(process.env.YANDEX_CLIENT_ID&&process.env.YANDEX_CLIENT_SECRET&&process.env.PUBLIC_BASE_URL);
function cookies(r){return Object.fromEntries(String(r.headers.cookie??'').split(';').map(x=>x.trim().split('=')).filter(([k])=>k));}
function send(r,s,b,h={}){r.writeHead(s,{'content-type':'text/html; charset=utf-8',...h});r.end(b);}function redirect(r,l,c){r.writeHead(303,{location:l,...(c?{'set-cookie':c}:{})});r.end();}
function cookie(t,max=days*86400){return`mc_session=${t}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${max}${process.env.NODE_ENV==='production'?'; Secure':''}`;}
async function form(r){const a=[];for await(const c of r){a.push(c);if(Buffer.concat(a).length>65536)throw Error('too_large');}const params=new URLSearchParams(Buffer.concat(a).toString()),result=Object.fromEntries(params);for(const key of new Set(params.keys())){const values=params.getAll(key);if(values.length>1)result[key]=values;}return result;}
const ip=r=>r.socket.remoteAddress??'unknown';async function user(r){const t=cookies(r).mc_session;return t?findSession(hashToken(t)):null;}
function sameOrigin(r){const origin=r.headers.origin;if(!origin)return true;try{return new URL(origin).host===r.headers.host;}catch{return false;}}
function logWbConnectionFailure(error,{userId,storeId}){console.warn('[WB connection failed]',JSON.stringify({time:new Date().toISOString(),error:error?.message||'unknown',dbCode:error?.code||undefined,wbStatus:error?.status||undefined,endpoint:error?.endpoint||undefined,missingScopes:error?.missingScopes||undefined,userId,storeId}));}
async function session(r,id){const{token,tokenHash}=createSessionToken();await saveSession({userId:id,tokenHash,expiresAt:new Date(Date.now()+days*86400000)});redirect(r,'/',cookie(token));}
async function captchaOk(token,requestIp){if(!process.env.SMARTCAPTCHA_SERVER_KEY)return true;const body=new URLSearchParams({secret:process.env.SMARTCAPTCHA_SERVER_KEY,token:token??'',ip:requestIp});const response=await fetch('https://smartcaptcha.cloud.yandex.ru/validate',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body});return response.ok&&(await response.json()).status==='ok';}
async function sendSettings(res,status,current,stores,options={}){const store=stores[0],catalog=store?await getCatalogState(current.user_id,store.id):null;const due=!catalog?.stream?.next_run_at||new Date(catalog.stream.next_run_at)<=new Date(),stale=catalog?.stream?.run_status==='running'&&new Date(catalog.stream.started_at)<=new Date(Date.now()-30*60*1000);if(store?.connected&&(catalog?.stream?.run_status!=='running'||stale)&&due)scheduleCatalogSync(current.user_id,store.id);return send(res,status,settingsPage(current,stores,{...options,catalog,billing:await getBillingSummary(current.user_id)}));}
async function sendProducts(res,status,current,stores,options={}){const store=stores[0],catalog=store?await getCatalogState(current.user_id,store.id):null;return send(res,status,productsPage(current,stores,catalog,await getBillingSummary(current.user_id),options));}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host??'localhost'}`);
 if(req.method==='GET'&&url.pathname==='/health')return send(res,200,'ok',{'content-type':'text/plain'});
 if(req.method==='GET'&&['/styles.css','/favicon.svg','/ui.css','/ui.js','/brand.png','/products.png','/interface.ttf'].includes(url.pathname)){const f=path.join(path.resolve('app/public'),url.pathname.slice(1));const types={'.css':'text/css','.svg':'image/svg+xml','.js':'text/javascript','.png':'image/png','.ttf':'font/ttf'};res.writeHead(200,{'content-type':types[path.extname(f)],'x-content-type-options':'nosniff'});return res.end(await readFile(f));}
 const current=await user(req);const page=(mode,extra={})=>authPage({mode,yandexEnabled,...extra});
 if(req.method==='GET'&&url.pathname==='/'){if(!current)return redirect(res,'/login');const stores=await listStores(current.user_id);return stores.length?send(res,200,overviewPage(current,stores)):redirect(res,'/onboarding/store');}
 if(req.method==='GET'&&uiRoutes.has(url.pathname)){if(!current)return redirect(res,'/login');const stores=await listStores(current.user_id);if(url.pathname==='/onboarding/store')return send(res,200,storeOnboardingPage(current));if(url.pathname==='/password')return send(res,200,passwordPage(current,stores));if(url.pathname==='/tariff')return send(res,200,tariffPage(current,stores,await getBillingSummary(current.user_id)));if(url.pathname==='/products'){const notice=url.searchParams.get('updated')==='1'?'Выбранные товары добавлены в аналитику.':url.searchParams.get('catalog')==='started'?'Обновление каталога запущено.':'';return sendProducts(res,200,current,stores,{notice});}if(url.pathname==='/settings'){const notice=url.searchParams.get('profile')==='updated'?'Данные аккаунта сохранены.':url.searchParams.get('password')==='changed'?'Пароль изменён. Другие активные сеансы завершены.':url.searchParams.get('connection')==='connected'?'Wildberries подключён. Начинаем загрузку каталога.':url.searchParams.get('catalog')==='started'?'Обновление каталога запущено.':url.searchParams.get('products')==='selected'?'Товары для анализа подтверждены.':'';return sendSettings(res,200,current,stores,{notice});}return send(res,200,url.pathname==='/overview'?overviewPage(current,stores):placeholderPage({...current,stores},url.pathname));}
 if(req.method==='POST'&&url.pathname==='/account/profile'){if(!current)return redirect(res,'/login');const d=await form(req);try{await updateProfile(current.user_id,d.displayName);return redirect(res,'/settings?profile=updated#account');}catch(e){if(e.message==='invalid_display_name'){const stores=await listStores(current.user_id);return sendSettings(res,422,current,stores,{error:'Введите имя от 2 до 80 символов.'});}throw e;}}
 if(req.method==='POST'&&url.pathname==='/password'){if(!current)return redirect(res,'/login');const d=await form(req),validated=validatePasswordChange(d),stores=await listStores(current.user_id);if(validated.error)return send(res,422,passwordPage(current,stores,{error:validated.error}));const limit=await takeLimit(`password:${current.user_id}:${ip(req)}`,5,15);if(!limit.allowed)return send(res,429,passwordPage(current,stores,{error:'Слишком много попыток. Повторите через 15 минут.'}));const credential=await getPasswordCredential(current.user_id);if(!credential)return send(res,409,passwordPage(current,stores,{error:'Для входа через Яндекс пароль пока недоступен.'}));if(!(await verifyPassword(validated.value.currentPassword,credential.password_hash)))return send(res,422,passwordPage(current,stores,{error:'Текущий пароль указан неверно.'}));const passwordHash=await hashPassword(validated.value.newPassword),tokenHash=hashToken(cookies(req).mc_session);await replacePassword(current.user_id,passwordHash,tokenHash);return redirect(res,'/settings?password=changed#account');}
 if(req.method==='POST'&&url.pathname==='/connections/wb'){if(!current)return redirect(res,'/login');if(!sameOrigin(req))return send(res,403,'Запрос отклонён. Обновите страницу и повторите подключение.');const d=await form(req),stores=await listStores(current.user_id);if(!stores.some(store=>store.id===d.storeId))return sendSettings(res,404,current,stores,{error:'Магазин не найден.'});const limit=await takeLimit(`wb-connect:${current.user_id}`,5,15);if(!limit.allowed)return sendSettings(res,429,current,stores,{error:'Слишком много проверок токена. Повторите через 15 минут.'});try{const verified=await verifyWbToken(d.token),encrypted=encryptSecret(verified.token);if(!verified.sellerInfoAvailable)console.warn('[WB seller-info skipped]',JSON.stringify({time:new Date().toISOString(),reason:'rate_limited',userId:current.user_id,storeId:d.storeId}));await saveWbConnection(current.user_id,{storeId:d.storeId,sellerId:verified.sellerId,scopes:verified.scopes,encrypted});scheduleCatalogSync(current.user_id,d.storeId,{force:true});return redirect(res,'/settings?connection=connected#store');}catch(e){logWbConnectionFailure(e,{userId:current.user_id,storeId:d.storeId});const messages={wb_token_invalid:'Не удалось прочитать токен Wildberries.',wb_token_expired:'Срок действия токена Wildberries истёк.',wb_test_token_unsupported:'Для загрузки реальных данных нужен базовый или персональный токен, а не тестовый.',wb_token_type_unsupported:'Используйте базовый или персональный токен Wildberries.',wb_write_token_forbidden:'Создайте токен с доступом только для чтения.',wb_scopes_missing:'В токене не хватает категорий «Контент», «Аналитика», «Статистика» или «Финансы».',wb_token_rejected:'Wildberries отклонил токен. Проверьте токен и его категории доступа.',wb_rate_limited:'Wildberries временно ограничил проверку токена. Повторите через минуту.',wb_unavailable:'Не удалось связаться с Wildberries. Попробуйте позже.',wb_seller_mismatch:'Токен содержит несовпадающие данные кабинета Wildberries.',wb_encryption_not_configured:'Безопасное хранилище токенов пока не настроено.',store_account_mismatch:'Этот магазин уже связан с другим кабинетом Wildberries.',store_not_found:'Магазин не найден.',connection_write_forbidden:'Недостаточно прав для подключения магазина.'};const status=e.message==='wb_encryption_not_configured'?503:e.message==='wb_rate_limited'?429:e.message==='wb_unavailable'?502:e.message==='store_not_found'?404:e.message==='connection_write_forbidden'?403:e.message==='store_account_mismatch'?409:messages[e.message]?422:500;return sendSettings(res,status,current,stores,{error:messages[e.message]||'Внутренняя ошибка подключения. Причина записана в журнал службы.'});}}
 if(req.method==='POST'&&url.pathname==='/catalog/sync'){if(!current)return redirect(res,'/login');if(!sameOrigin(req))return send(res,403,'Запрос отклонён.');const d=await form(req),stores=await listStores(current.user_id);if(!stores.some(store=>store.id===d.storeId&&store.connected)){if(d.returnTo==='/products')return sendProducts(res,404,current,stores,{error:'Подключённый магазин не найден.'});return sendSettings(res,404,current,stores,{error:'Подключённый магазин не найден.'});}scheduleCatalogSync(current.user_id,d.storeId,{force:true});return redirect(res,d.returnTo==='/products'?'/products?catalog=started':'/settings?catalog=started#products');}
 if(req.method==='POST'&&url.pathname==='/products/select'){if(!current)return redirect(res,'/login');if(!sameOrigin(req))return send(res,403,'Запрос отклонён.');const d=await form(req),stores=await listStores(current.user_id),productIds=(Array.isArray(d.productIds)?d.productIds:[d.productIds]).filter(value=>/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(String(value??'')));try{const store=stores.find(item=>item.id===d.storeId);if(!store)throw new Error('store_not_found');const catalog=await getCatalogState(current.user_id,store.id);if(catalog.selection)await addProductsToSelection(current.user_id,{storeId:d.storeId,productIds});else await confirmProductSelection(current.user_id,{storeId:d.storeId,productIds});return redirect(res,'/products?updated=1');}catch(e){const messages={catalog_not_ready:'Каталог ещё не загружен.',selection_write_forbidden:'Недостаточно прав для выбора товаров.',store_not_found:'Магазин не найден.'};const message=messages[e.message]||(String(e.message).includes('already selected')?'Один из товаров уже выбран. Обновите страницу.':String(e.message).includes('product limit')?'Лимит товаров текущего тарифа уже достигнут.':'Не удалось добавить товары. Проверьте выбранный список.');return sendProducts(res,e.message==='selection_write_forbidden'?403:e.message==='store_not_found'?404:422,current,stores,{error:message});}}
 if(req.method==='POST'&&url.pathname==='/stores'){if(!current)return redirect(res,'/login');const d=await form(req);try{await createPendingStore(current.user_id,d.name);return redirect(res,'/settings#store');}catch(e){if(e.message==='invalid_store_name')return send(res,422,storeOnboardingPage(current,{error:'Введите название от 2 до 80 символов.',value:d.name}));if(e.message==='store_write_forbidden')return send(res,403,storeOnboardingPage(current,{error:'Недостаточно прав для добавления магазина.',value:d.name}));if(e.code==='23514')return send(res,409,storeOnboardingPage(current,{error:'Текущий тариф не позволяет добавить ещё один магазин.',value:d.name}));throw e;}}
 if(req.method==='GET'&&url.pathname==='/login')return current?redirect(res,'/'):send(res,200,page('login'));
 if(req.method==='GET'&&url.pathname==='/register')return current?redirect(res,'/'):send(res,200,page('register'));
 if(req.method==='POST'&&url.pathname==='/register'){const d=await form(req),v=validateRegistration(d),limit=await takeLimit(`register:ip:${ip(req)}`,5,60);if(v.error)return send(res,422,page('register',{error:v.error,values:d}));if(!limit.allowed)return send(res,429,page('register',{error:'Слишком много регистраций. Повторите позже.',values:d,captchaKey:process.env.SMARTCAPTCHA_CLIENT_KEY}));if(limit.attempts>=3&&!(await captchaOk(d['smart-token'],ip(req))))return send(res,422,page('register',{error:'Подтвердите, что вы не робот.',values:d,captchaKey:process.env.SMARTCAPTCHA_CLIENT_KEY}));if(await findPasswordUser(v.value.email))return send(res,409,page('register',{error:'Аккаунт с таким email уже существует.',values:d}));const passwordHash=await hashPassword(v.value.password);if(!requiresEmailVerification()){const created=await registerUser({...v.value,passwordHash});return session(res,created.id);}const code=createVerificationCode();await saveChallenge({...v.value,passwordHash,codeHash:hashToken(code)});const mode=await sendVerificationCode(v.value.email,code);return send(res,200,verifyPage({email:v.value.email,devCode:mode==='development'?code:''}));}
 if(req.method==='POST'&&url.pathname==='/verify-email'){const d=await form(req),email=normalizeEmail(d.email),limit=await takeLimit(`verify:${email}`,5,15);if(!limit.allowed)return send(res,429,verifyPage({email,error:'Слишком много попыток. Запросите новый код позже.'}));const ch=await consumeChallenge(email,hashToken(d.code));if(!ch)return send(res,422,verifyPage({email,error:'Неверный или просроченный код.'}));const created=await registerUser({name:ch.display_name,email,passwordHash:ch.password_hash});await markVerified(created.id);return session(res,created.id);}
 if(req.method==='POST'&&url.pathname==='/login'){const d=await form(req),email=normalizeEmail(d.email),limit=await takeLimit(`login:${ip(req)}:${email}`,10,15);if(!limit.allowed)return send(res,429,page('login',{error:'Слишком много попыток. Повторите через 15 минут.',values:{email}}));const f=await findPasswordUser(email),ok=await verifyPassword(d.password,f?.password_hash??dummyHash);if(!f||!ok||f.status!=='active')return send(res,401,page('login',{error:'Неверный email или пароль.',values:{email}}));return session(res,f.id);}
 if(req.method==='GET'&&url.pathname==='/auth/yandex'){if(!yandexEnabled)return send(res,503,'Яндекс ID пока не настроен.');const{token,stateHash}=createSessionToken();await saveOauthState(stateHash);const q=new URLSearchParams({response_type:'code',client_id:process.env.YANDEX_CLIENT_ID,redirect_uri:`${process.env.PUBLIC_BASE_URL}/auth/yandex/callback`,state:token});return redirect(res,`https://oauth.yandex.ru/authorize?${q}`);}
 if(req.method==='GET'&&url.pathname==='/auth/yandex/callback'){if(!await consumeOauthState(hashToken(url.searchParams.get('state'))))return send(res,400,'Ссылка входа устарела.');const body=new URLSearchParams({grant_type:'authorization_code',code:url.searchParams.get('code')??'',client_id:process.env.YANDEX_CLIENT_ID,client_secret:process.env.YANDEX_CLIENT_SECRET});const tr=await fetch('https://oauth.yandex.ru/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body});if(!tr.ok)return send(res,401,'Не удалось войти через Яндекс.');const tok=await tr.json(),info=await fetch('https://login.yandex.ru/info?format=json',{headers:{authorization:`OAuth ${tok.access_token}`}}),p=await info.json();const u=await findOrCreateYandexUser({subject:String(p.id),email:p.default_email??null,name:p.display_name??p.real_name??'Пользователь Яндекса'});return session(res,u.id);}
 if(req.method==='POST'&&url.pathname==='/logout'){const t=cookies(req).mc_session;if(t)await deleteSession(hashToken(t));return redirect(res,'/login',cookie('',0));}return send(res,404,'Страница не найдена');
 }catch(e){console.error(e);return send(res,500,'Не удалось выполнить запрос. Попробуйте ещё раз.');}});
await migrate();server.listen(port,'0.0.0.0',()=>console.log(`Marketplace Control: http://localhost:${port}`));async function stop(){server.close();await pool.end();}process.on('SIGTERM',stop);process.on('SIGINT',stop);
